### ISSUE TITLE
Where the graphics are!

### ISSUE THREAD

**Issue by UncleBobTheCoder** [theTechnoKid/RocketWarfare#58]
I'll add more once I get rolling.

**Comment by UncleBobTheCoder** [comment]
![basic body part](https://cloud.githubusercontent.com/assets/10384139/15985746/669d5826-2fc5-11e6-902e-096f68328877.png)

**Comment by theTechnoKid** [comment]
The graphics are located in the `res/images` folder. You will find the `spritesheet.png` file there. You can put any other graphics there, like the logo or banner.
