### ISSUE TITLE
Spritesheet Transperency

### ISSUE THREAD

**Issue by UncleBobTheCoder** [theTechnoKid/RocketWarfare#61]
I figured out how to make the background of the spritesheet transparent, should I make it transparent, or keep the background white?

**Comment by theTechnoKid** [comment]
@UncleBobTheCoder Make it transparent, please. Also, make sure the file names are `spritesheet_*rockettype*.png`, where `*rockettype*` is the type of rocket. Additionally, you don't have to make the flipped version of the wings and missiles I can do that in the code. Just do the right side.
